name: Auto PR and Merge

on:
  push:
    branches: [ jeffrey ]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Create PR and DEBUG outputs
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        id: create-pr
        with:
          title: "Auto PR: jeffrey → master"
          base: master
          branch: jeffrey
          delete-branch: false

      # 2. Print PR details (debugging)
      - name: Debug PR Outputs
        if: always()
        run: |
          echo "PR Number: ${{ steps.create-pr.outputs.pull-request-number }}"
          echo "PR URL: ${{ steps.create-pr.outputs.pull-request-url }}"
          echo "PR Created: ${{ steps.create-pr.outputs.pull-request-created }}"

      # 3. Auto-merge (directly use PR number from create-pr)
      - name: Auto-merge PR
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const prNumber = ${{ steps.create-pr.outputs.pull-request-number }};
              console.log(`Attempting to merge PR #${prNumber}...`);
              
              const response = await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'merge'
              });
              console.log('✅ Response:', JSON.stringify(response.data));
            } catch (error) {
              console.error('❌ FULL ERROR:', JSON.stringify(error, null, 2));
              // Non-blocking error
              core.setFailed(`Merge failed: ${error.message}`);
            }