name: Auto PR from jeffrey to master

on:
  push:
    branches:
      - jeffrey

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: jeffrey
          base: master
          title: 'Auto PR: Merge jeffrey into master'
          body: 'This pull request was automatically created by GitHub Actions.'

      - name: Auto-merge Pull Request
        if: steps.create_pr.outputs.pull-request-url != ''
        run: |
          gh pr merge "${{ steps.create_pr.outputs.pull-request-url }}" --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
